#!/bin/sh
set -e

# SRC should be a FULL path as seen inside the container.
SRC="$SRC"

if [ -z "$SRC" ]; then
  echo "ERROR: You must pass the source file via -e SRC=/path/to/file.mkv"
  exit 1
fi

if [ ! -f "$SRC" ]; then
  echo "ERROR: File not found inside container: $SRC"
  echo "Make sure the path starts with /media, /mnt/media, /mnt/media1, or your mounted media path"
  exit 1
fi

# Default suffix for transcoded files
SUFFIX="${SUFFIX:-TSD}"

DIR=$(dirname "$SRC")
BASE=$(basename "$SRC")
EXT="${BASE##*.}"
NAME="${BASE%.*}"

# 🔒 Skip if this file already looks TSD-tagged
LOWER_NAME=$(printf '%s\n' "$NAME" | tr 'A-Z' 'a-z')
if echo "$LOWER_NAME" | grep -q -- '-tsd$'; then
  echo "INFO: Source already has -TSD tag, skipping encode: $SRC"
  exit 0
fi

OUT="${DIR}/${NAME}-${SUFFIX}.${EXT}"

# Preset info comes from env, set by jobs.py based on preset key
PRESET_FILE="${HB_PRESET_FILE:-/presets/my-presets.json}"
PRESET_NAME="${HB_PRESET_NAME:-MyPresetName}"
EXTRA_ARGS="${HB_EXTRA_ARGS:-}"

# GPU mode:
#   auto      = use FFmpeg VAAPI when a qsv_* encoder is requested, otherwise HandBrakeCLI
#   vaapi     = force FFmpeg VAAPI
#   handbrake = force HandBrakeCLI
TSD_GPU_MODE="${TSD_GPU_MODE:-auto}"
VAAPI_DEVICE="${VAAPI_DEVICE:-/dev/dri/renderD128}"

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------
json_get_first_video_value() {
  key="$1"
  file="$2"
  if command -v jq >/dev/null 2>&1 && [ -f "$file" ]; then
    jq -r ".. | objects | select(has(\"$key\")) | .${key} | select(. != null)" "$file" 2>/dev/null | head -n 1
  fi
}

arg_value() {
  # Very small parser for the HandBrake args generated by the app.
  # Supports: --encoder qsv_h265, --encoder=qsv_h265, -e qsv_h265, -b 2500, --vb 2500, --width 1920, etc.
  wanted="$1"
  set -- $EXTRA_ARGS
  while [ "$#" -gt 0 ]; do
    case "$1" in
      "$wanted")
        shift
        [ "$#" -gt 0 ] && printf '%s\n' "$1"
        return 0
        ;;
      "$wanted"=*)
        printf '%s\n' "${1#*=}"
        return 0
        ;;
    esac
    shift
  done
  return 1
}

first_nonempty() {
  for v in "$@"; do
    if [ -n "$v" ] && [ "$v" != "null" ]; then
      printf '%s\n' "$v"
      return 0
    fi
  done
  return 1
}

# Read encoder/bitrate/size from app extra args first, then preset JSON.
ENCODER=$(first_nonempty \
  "$(arg_value --encoder || true)" \
  "$(arg_value -e || true)" \
  "$(json_get_first_video_value VideoEncoder "$PRESET_FILE" || true)" \
  "")

VIDEO_BITRATE=$(first_nonempty \
  "$(arg_value -b || true)" \
  "$(arg_value --vb || true)" \
  "$(json_get_first_video_value VideoAvgBitrate "$PRESET_FILE" || true)" \
  "$(json_get_first_video_value VideoBitrate "$PRESET_FILE" || true)" \
  "2500")

OUT_WIDTH=$(first_nonempty "$(arg_value --width || true)" "")
OUT_HEIGHT=$(first_nonempty "$(arg_value --height || true)" "")

# HandBrake-style thread option for software encodes only.
HB_THREAD_OPTS=""
if [ -n "$HB_THREADS" ]; then
  case "$HB_THREADS" in
    *[!0-9]*)
      echo "INFO: Ignoring non-numeric HB_THREADS value: $HB_THREADS" ;;
    *)
      if [ "$HB_THREADS" -gt 0 ] 2>/dev/null; then
        HB_THREAD_OPTS="--encopts threads=$HB_THREADS"
        echo "INFO: Using HB_THREADS=$HB_THREADS (HB_THREAD_OPTS: $HB_THREAD_OPTS)"
      fi ;;
  esac
fi

# Safety: don't overwrite an existing output file
if [ -f "$OUT" ]; then
  echo "ERROR: Output already exists: $OUT"
  echo "Refusing to overwrite. Delete/rename it first."
  exit 1
fi

LOWER_ENCODER=$(printf '%s\n' "$ENCODER" | tr 'A-Z' 'a-z')
USE_VAAPI=0
if [ "$TSD_GPU_MODE" = "vaapi" ]; then
  USE_VAAPI=1
elif [ "$TSD_GPU_MODE" = "auto" ] && echo "$LOWER_ENCODER" | grep -q '^qsv_'; then
  USE_VAAPI=1
fi

# ------------------------------------------------------------
# FFmpeg VAAPI GPU path
# This replaces broken HandBrake QSV for Intel GPU encodes.
# ------------------------------------------------------------
if [ "$USE_VAAPI" -eq 1 ]; then
  if [ ! -e "$VAAPI_DEVICE" ]; then
    echo "ERROR: VAAPI device not found: $VAAPI_DEVICE"
    echo "Make sure docker-compose maps /dev/dri:/dev/dri and group_add includes video/render IDs."
    exit 1
  fi

  case "$LOWER_ENCODER" in
    *h264*)
      FFMPEG_ENCODER="h264_vaapi"
      FORMAT_FILTER="format=nv12,hwupload"
      PROFILE_ARGS=""
      ;;
    *h265*|*hevc*|"")
      FFMPEG_ENCODER="hevc_vaapi"
      if echo "$LOWER_ENCODER" | grep -q '10bit'; then
        FORMAT_FILTER="format=p010,hwupload"
        PROFILE_ARGS="-profile:v main10"
      else
        FORMAT_FILTER="format=nv12,hwupload"
        PROFILE_ARGS=""
      fi
      ;;
    *)
      echo "WARNING: Encoder '$ENCODER' is not supported by VAAPI mode. Falling back to hevc_vaapi."
      FFMPEG_ENCODER="hevc_vaapi"
      FORMAT_FILTER="format=nv12,hwupload"
      PROFILE_ARGS=""
      ;;
  esac

  SCALE_FILTER=""
  if [ -n "$OUT_WIDTH" ] && [ -n "$OUT_HEIGHT" ]; then
    SCALE_FILTER=",scale_vaapi=w=${OUT_WIDTH}:h=${OUT_HEIGHT}"
  fi

  echo "=== TSD FFmpeg VAAPI encode ==="
  echo "Source : $SRC"
  echo "Target : $OUT"
  echo "Suffix : -$SUFFIX"
  echo "Preset file : $PRESET_FILE"
  echo "Preset name : $PRESET_NAME"
  echo "Requested encoder : ${ENCODER:-auto}"
  echo "Using encoder : $FFMPEG_ENCODER"
  echo "VAAPI device : $VAAPI_DEVICE"
  echo "Video bitrate : ${VIDEO_BITRATE}k"
  if [ -n "$OUT_WIDTH" ] && [ -n "$OUT_HEIGHT" ]; then
    echo "Resize : ${OUT_WIDTH}x${OUT_HEIGHT}"
  fi
  echo "================================"

  # Copy all streams, chapters, and metadata. Re-encode only the primary video stream.
  # Audio/subtitles are copied to avoid losing English/Spanish/subtitle tracks.
  # Note: HandBrake progress parsing does not understand raw FFmpeg progress, so the UI
  # may stay near 0% until the job completes, but the encode itself uses the GPU.
  # shellcheck disable=SC2086
  ffmpeg -y -hide_banner \
    -vaapi_device "$VAAPI_DEVICE" \
    -i "$SRC" \
    -map 0 \
    -map_chapters 0 \
    -map_metadata 0 \
    -vf "${FORMAT_FILTER}${SCALE_FILTER}" \
    -c copy \
    -c:v:0 "$FFMPEG_ENCODER" \
    $PROFILE_ARGS \
    -b:v:0 "${VIDEO_BITRATE}k" \
    "$OUT"

else
  # ------------------------------------------------------------
  # HandBrake software path
  # Use this for x264/x265/SVT-AV1/etc. Avoid qsv_* here because the
  # Debian handbrake-cli package can fail with: qsv not available.
  # ------------------------------------------------------------
  echo "=== HandBrake one-shot encode ==="
  echo "Source : $SRC"
  echo "Target : $OUT"
  echo "Suffix : -$SUFFIX"
  echo "Preset file : $PRESET_FILE"
  echo "Preset name : $PRESET_NAME"
  echo "Detected encoder : ${ENCODER:-preset default}"
  echo "=================================="

  if [ -f "$PRESET_FILE" ]; then
    echo "Using preset file + preset name..."
    HandBrakeCLI \
      --preset-import-file "$PRESET_FILE" \
      -Z "$PRESET_NAME" \
      ${HB_THREAD_OPTS} \
      ${EXTRA_ARGS} \
      -i "$SRC" \
      -o "$OUT"
  else
    echo "WARNING: Preset file not found, using basic fallback settings..."
    HandBrakeCLI \
      ${HB_THREAD_OPTS} \
      -i "$SRC" \
      -o "$OUT" \
      -e x264 -q 20 -B 160
  fi
fi

# ------------------------------------------------------------
# Post-encode checks
# ------------------------------------------------------------
if [ ! -f "$OUT" ]; then
  echo "ERROR: Encode failed, output file not found."
  exit 1
fi

if [ ! -s "$OUT" ]; then
  echo "ERROR: Encode failed, output file is empty."
  exit 1
fi

echo "Done!"
echo "New file: $OUT"
echo "Source kept for app-level validation: $SRC"
